### ISSUE TITLE
Репозиторий жив?

### ISSUE THREAD

**Issue by sergeyklay** [vanchelo/phalcon-console#4]
Привет

Проект жив?
Нет желания добавить поддержку Phalcon 2.x и перевести всё на английский?

**Comment by vanchelo** [comment]
Жив конечно, конечно добавлю) Может ваш пулл реквест принять?

**Comment by sergeyklay** [comment]
Я его отменил потому что в том пулл реквесте в README человек указал ссылку на другой репозиторий, не на ваш.
```diff
-  "require": {
-    "vanchelo/phalcon-console": "dev-master"
-  }
+    "repositories": [
+        {
+            "type": "vcs",
+            "url": "https://github.com/teepluss/phalcon-console"
+        }
+    ],
+    "require": {
+        "vanchelo/phalcon-console": "dev-master"
+    }
```

В принципе можно принять и отдельным коммитом убрать те изменения.

**Comment by vanchelo** [comment]
Да, можно отдельным коммитом

**Comment by sergeyklay** [comment]
https://github.com/vanchelo/phalcon-console/pull/3

**Comment by sergeyklay** [comment]
Добавил в список https://github.com/sergeyklay/awesome-phalcon/pull/38
